# Default values for ai-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 5

image:
  repository: ai-app-docker-image
  # Use a specific version for stability to avoid 'latest' in production
  tag: "v1.0.0"
  # Change to 'IfNotPresent' if images are managed through CI/CD or pre-pulled
  pullPolicy: IfNotPresent

# Configuration for resource limits and requests
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 3000

# Health checks for better pod management
livenessProbe:
  httpGet:
    path: /healthz
    port: 3000
  initialDelaySeconds: 3
  periodSeconds: 3

readinessProbe:
  httpGet:
    path: /ready
    port: 3000
  initialDelaySeconds: 3
  periodSeconds: 3

# ENVs
env:
  - name: ENV_VAR_NAME
    value: "development"

# Example for environment variables from secrets
envFrom:
  - secretRef:
      name: ai-app-secrets
