replicaCount: 5
image:
  repository: ai-app-docker-image
  tag: latest
  pullPolicy: Always
resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"
service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

